agsProdPath="$HOME/dots/homes/stef/programs/widgets/ags/config"
currentPath=$(pwd)

cp -r "$currentPath/@girs" "$agsProdPath"
cp -r "$currentPath/bar" "$agsProdPath"
cp -r "$currentPath/constants" "$agsProdPath"
cp -r "$currentPath/icons" "$agsProdPath"
cp -r "$currentPath/launcher" "$agsProdPath"
cp -r "$currentPath/node_modules" "$agsProdPath"
cp -r "$currentPath/notifications" "$agsProdPath"
cp -r "$currentPath/osd" "$agsProdPath"
cp -r "$currentPath/sessionMenu" "$agsProdPath"
cp -r "$currentPath/types" "$agsProdPath"
cp -r "$currentPath/util" "$agsProdPath"
cp -r "$currentPath/app.tsx" "$agsProdPath"
cp -r "$currentPath/biome.json" "$agsProdPath"
cp -r "$currentPath/env.d.ts" "$agsProdPath"
cp -r "$currentPath/package-lock.json" "$agsProdPath"
cp -r "$currentPath/package.json" "$agsProdPath"
cp -r "$currentPath/style.scss" "$agsProdPath"
cp -r "$currentPath/tsconfig.json" "$agsProdPath"